[build]
  # Directorio que Netlify desplegará. La raíz de tu proyecto.
  publish = "."
  
  # Comando que Netlify ejecutará para construir tu sitio.
  # Esto instalará las dependencias (axios) y luego ejecutará tu script de build.
  command = "npm install && npm run build"
