backend:
  name: git-gateway
  branch: main

publish_mode: simple

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Imagen destacada", name: "featured_image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}
  
  - name: "pages"
    label: "Páginas"
    files:
      - label: "Página de Inicio"
        name: "home"
        file: "content/home.md"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Subtítulo", name: "subtitle", widget: "string"}
          - {label: "Contenido", name: "body", widget: "markdown"}
