backend:
  name: git-gateway
  branch: main

# Solo descomenta la siguiente línea si estás desarrollando localmente
# local_backend: true

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "blog"
    label: "Artículos del Blog"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Título del Artículo"
        name: "title"
        widget: "string"
      - label: "Fecha de Publicación"
        name: "date"
        widget: "datetime"
      - label: "Imagen Destacada"
        name: "thumbnail"
        widget: "image"
        required: false
      - label: "Leyenda de la Imagen"
        name: "caption"
        widget: "string"
        required: false
      - label: "Crédito de la Foto"
        name: "credit"
        widget: "string"
        required: false
      - label: "Categoría"
        name: "category"
        widget: "string"
      - label: "Subtítulo (Opcional)"
        name: "subtitle"
        widget: "string"
        required: false
      - label: "Cuerpo del Artículo"
        name: "body"
        widget: "markdown"
