backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "posts"
    label: "Posts del Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen Destacada", name: "featured_image", widget: "image" }
      - { label: "Categoría", name: "category", widget: "select", options: ["Marketing Digital", "Branding", "Desarrollo Web", "Inteligencia Artificial", "Estrategia", "General"] }
      - { label: "Extracto", name: "excerpt", widget: "text" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - { label: "Destacado", name: "featured", widget: "boolean", default: false }
