backend:
  name: git-gateway
  branch: main

media_folder: "assets/blog"
public_folder: "assets/blog"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL amigable (ej: mi-articulo-genial)" }
      - { label: "Categoría", name: "categoria", widget: "select", options: ["Desarrollo Web", "Branding", "Inteligencia Artificial", "Marketing", "Emprendimiento"] }
      - { label: "Fecha de publicación", name: "fecha", widget: "date" }
      - { label: "Autor", name: "autor", widget: "string", default: "Ronald Rangel" }
      - { label: "Destacado", name: "destac
