backend:
  name: git-gateway
  branch: main

media_folder: "assets/img/uploads" # Guardaremos imágenes en una carpeta más ordenada
public_folder: "/assets/img/uploads"

collections:
  - name: "blog"
    label: "Artículos del Blog"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha de Publicación", name: "date", widget: "datetime" }
      - { label: "Imagen Destacada", name: "thumbnail", widget: "image" }
      - { label: "Leyenda de la Foto", name: "caption", widget: "string", required: false }
      - { label: "Crédito de la Foto", name: "credit", widget: "string", required: false }
      - { label: "Categoría", name: "category", widget: "string" }
      - { label: "Subtítulo", name: "subtitle", widget: "string", required: false }
      - { label: "Recuadro Destacado", name: "highlight_box", widget: "text", required: false }
      - { label: "Cuerpo del Artículo", name: "body", widget: "markdown" }
